### PR TITLE
ci: Add Binder build trigger

### PR DESCRIPTION
**Pull request by matthewfeickert**
This PR does a few things:

- First, it moves Binder related files to a top level directory `binder/` as if this directory exists Binder will only look in it for configuration files and ignore all others. A [`postBuild` config file](https://mybinder.readthedocs.io/en/latest/config_files.html#postbuild-run-code-after-installing-the-environment) is then used to install all of the Python dependencies in various `requirements.txt` files that are needed by the notebooks.

- Add GitHub Actions workflow and shell script to trigger Binder builds of the repo on the GKE cluster of the Binder Federation (most common one to get requests from North America) upon successful merge of a PR into `master`. Look at `pyhf`'s workflows for examples of this in action.

- The Binder badge is made to use the [`?urlpath=lab/tree/book` URL appendix](https://github.com/binder-examples/jupyterlab) to have Binder open Jupyter Lab in the `book/` directory upon launch (as there is no obvious default notebook to open up into). [Binder](https://mybinder.org/v2/gh/cranmer/stats-ds-book/master?urlpath=lab/tree/book)

- Tonight (2020-08-18) `myst-parser` (which gets picked up in `jupytext[myst]`)  [released `v0.12.0`](https://pypi.org/project/myst-parser/0.12.0/#history) which is incompatible with `myst-nb` (I think) resulting in build errors. By explicitly adding `myst-parser~=1.11.1` to `book/requirements.txt` this restricts the allowed range of `myst-parser` to `v1.11.X`, allowing for builds to succeed.

- Finally, .DS_store files are binaries that MacOS makes for searching and shouldn't be in Git repos, so they're both removed (no need to keep them) and a `.gitignore` file is made with their pattern in in.

## Suggested squash and merge commit log

```
* Use Binder postBuild configuration file to install Python dependencies
   - c.f. https://mybinder.readthedocs.io/en/latest/config_files.html#postbuild-run-code-after-installing-the-environment
* Add GHA workflow to trigger Binder build on PR merge
* Restrict myst-parser to v1.11.X range to give compatible release for myst-nb
* Update Binder badge to launch into Jupyter Lab
* Remove and ignore .DS_store
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@cranmer This is ready for review.

**Comment by cranmer** [comment]
Wow, thanks a lot! I thought I had removed the .DS_store files, thanks for catching that.

**Comment by cranmer** [comment]
FYI: I got this with binder
image

**Comment by matthewfeickert** [comment]
> FYI: I got this with binder

ah. okay. Things should still work fine, but those extensions probably won't work out of the box (though you don't need them). All the notebooks still run fine though, yes? 

I can submit another PR later that properly does the jupyterlab build after install to get them from complaining.

**Pull request merged**
